
import HomePage from "@/src/pages/HomePage/HomePage";
import Head from "next/head";

export default function Home({ initialTasks }) {
  return (
    <>
      <Head>
        <title>Task Management App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
      >
        <HomePage initialTasks={initialTasks} />
      </div>
    </>
  );
}

  // Initial tasks fetched server-side
export const getServerSideProps = async () => {
  const tasks = [
    { id: 1, title: 'Make a task management app', description: 'The app should have the unctionality to display the task list in good manner and also have crud functionality in it', priority: 'high', completed: false,status:"In-Progress" },
    { id: 2, title: 'Task 2', description: 'Description 2', priority: 'medium', completed: false,status:"To-Do" },
  ];

  return {
    props: {
      initialTasks: tasks,
    },
  };
};
