
import HomePage from "@/src/pages/HomePage/HomePage";
import Head from "next/head";

export default function Home({ initialTasks }) {
  return (
    <>
      <Head>
        <title>Task Management App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
      >
        <HomePage initialTasks={initialTasks} />
      </div>
    </>
  );
}

  // Initial tasks fetched server-side
export const getServerSideProps = async () => {
  const tasks = [
    { id: 2, title: 'Manage the task Management', description: 'The app should be good at displaying the rows and column and well maintained', priority: 'high', completed: false,status:"In-Progress" },
    { id: 4, title: 'Manage the task Management', description: 'The app should be good at displaying the rows and column and well maintained', priority: 'medium', completed: false,status:"In-Progress" },
    { id: 3, title: 'Upload it ', description: 'And also keep the Readme file updated', priority: 'low', completed: false,status:"To-Do" },
    { id: 1, title: 'Make a task management app', description: 'The app should have the functionality to display the task list in good manner and also have crud functionality in it along with search functionality with title and name and sorting priority', priority: 'high', completed: false,status:"Completed" },

  ];

  return {
    props: {
      initialTasks: tasks,
    },
  };
};
